### ISSUE TITLE
7) CARACTERÍSTICAS BÁSICAS PYTHON

### ISSUE THREAD

**Issue by agusponceuria** [agusponceuria/Grupo-de-Estudio-4#10]

**Comment by Epaiz28** [comment]
H

**Comment by Epaiz28** [comment]
Python es un lenguaje de programación interpretado, multiparadigma y multiplataforma que fue creado por el ingeniero Guido Van Rossum. Este lenguaje se caracteriza principalmente como lenguaje por su sintaxis simple y expresiva, cuyo objetivo principal es aumentar la legibilidad y la facilidad de desarrollo. Veamos algunos ejemplos representativos de su sintaxis a través de métodos, funciones y tareas habituales durante el desarrollo. Una de las principales características de Python es que se trata de un lenguaje de programación orientado a objetos, otra de las características principales de Python es que se trata de un lenguaje de programación de código abierto.
Python es un código muy amable para todo tipo de desarrolladores, desde los que ya tienen experiencia con otros lenguajes como para los que están aprendiendo a programar desde cero.
