### ISSUE TITLE
3) FOR

### ISSUE THREAD

**Issue by agusponceuria** [agusponceuria/Grupo-de-Estudio-4#7]

**Comment by VictorAndPolo** [comment]
### Bucle for
Un bucle **for** se usa para iterar sobre una secuencia (es decir, una lista, una tupla, un diccionario, un conjunto o una cadena).

Esto se parece menos a la palabra clave **for** en otros lenguajes de programación y funciona más como un método iterador como se encuentra en otros lenguajes de programación orientados a objetos.

Con el bucle for podemos ejecutar un conjunto de sentencias, una vez por cada elemento de una lista, tupla, conjunto, etc.
Ejemplo:
```
frutas = ["Manzana", "Banana", "Tomate"]
for x in frutas:
  print(x)

Imprime en pantalla:
Manzana
Banana
Tomate
```
El ciclo **for** no requiere una variable de indexación para establecer de antemano.

**Bucle a través de una cadena**
Incluso las cadenas son objetos iterables, contienen una secuencia de caracteres:
Ejemplo:
Repasa las letras de la palabra "banana":

```
for x in "banana":
  print(x)

Imprime en pantalla:
b
a
n
a
n
a

```
También se puede interrumpir con un **break** por ejemplo sale del ciclo cuando x sea "banana", pero esta para antes de la impresión:
```

frutas = ["Manzana", "Banana", "Tomate"]
for x in frutas:
  if x == "Banana":
    break
  print(x)
Imprime:
Manzana
```
Con el uso de **continue** podemos parar o saltar la iteración actual del ciclo y continuar con la siguiente, ejemplo:
```
frutas = ["Manzana", "Banana", "Tomate"]
for x in frutas:
  if x == "Banana":
    break
  print(x)
Imprime:
Manzana
Tomate
```
Con la función **range()** podemos devolver secuencia de números si quisiéramos, ejemplo:
```
for x in range (4):
    print(x)
Imprime:
0
1
2
3
```
Tengamos en cuenta que range(4) imprime 4 dígitos desde cero a menos que le agreguemos un valor inicial como por ejemplo:
for x in range(1, 5):
print(x)
```
Imprime:
2
3
4
```
También podemos configurar el incremento de range(), ejemplo:
```
for x in range(0,21,5):
    print(x)
Imprime:
5
10
15
20
```
Notemos que la función considera el 0 como base inicial y 21 como su fin, siendo el salto cada 5 números, si la función fuera (0,20,5) imprimiría en pantalla hasta 15.

**Comment by Unbroken13** [comment]
Bucles For en Python

Sentencias bucles for
Python utiliza bucles for para iterar sobre una lista de elementos. A
diferencia de C o Java,  que utilizan el bucle for para cambiar un valor (una variable) en cada iteración y así poder acceder a los elementos de un arreglo (array) utilizando ese valor.

En Python los bucles for iteran sobre estructuras de datos basadas en colecciones como listas, tuplas y/o diccionarios.
La sintaxis básica es:

for valor in lista_de_valores:
  # puedes usar la variable valor dentro de este bloque de codigo

#for, in -->> son palabras reservadas del bucle for
#se puede leer de la siguiente forma:
#por cada <valor> en la <lista_de_valores>


En general, puedes utilizar cualquier cosa como valor del iterador, donde serán asignados los valores del objeto a iterar, Por ejemplo, puedes extraer una tupla de una lista de tuplas:

lista_tuplas = [(1,2), (3,4)]

for a, b in lista_tuplas:
  print("a:", a, "b:", b)
  
"""
a,b -> valor iterador
lista_tuplas -> objeto a iterar
Salida
a: 1 b: 2
a: 3 b: 4
"""
Por otra parte, puedes recorrer cualquier objeto que sea iterable, puedes llamar a una función o iterar sobre una lista literal

for persona in cargar_personas():
  print("El nombre es:", persona.nombre)
for caracter in ["P", "y", "t", "h", "o", "n"]:
  print("Dame una '{}'!".format(caracter))
Diferentes formas de usar bucles For:

Iterar sobre la función range() - rango
for i in range(10):
    print(i)
En lugar de ser una función, range() en realidad es un tipo de secuencia inmutable. La secuencia resultante tendrá una lista desde el límite inferior, p. ej. cero, hasta el límite superior menos uno.
Por defecto el límite inferior o índice inicial será cero.

Resultado:

range(10)
>
0
1
2
3
4
5
6
7
8
9
>

range(5)
>
0
1
2
3
4
>
Adicionalmente, es posible especificar el límite inferior de la secuencia e incluso los pasos de la numeración añadiendo un segundo y tercer parámetro.

for i in range(4,10,2): #Secuencia del 4 al 9 , de 2 en 2
    print(i)
Resultado:

>
4
6
8
>

**Comment by Unbroken13** [comment]
Iterar sobre los valores de una lista o tupla
A = ["hola", 1, 65, "gracias", [2, 3]]
for value in A:
    print(value)
Resultado:

>
hola
1
65
gracias
[2, 3]
>

Iterar sobre claves en un diccionario (también conocido como hashmap)
fruta_a_color = {"manzana": "#ff0000",
                 "lima": "#ffff00",
                 "naranja": "#ffa500"}

for key in fruta_a_color:
    print(key, fruta_a_color[key])
Resultado:

>
manzana #ff0000
lima #ffff00
naranja #ffa500
>
